---
# Install and configure fail2ban for ssh and Apache protection
- name: Install fail2ban
  become: true
  apt: pkg=fail2ban
    state=present
    update_cache=yes

- name: Create local fail2ban config
  become: true
  command: cp /etc/fail2ban/jail.conf /etc/fail2ban/jail.local
    creates=/etc/fail2ban/jail.local
  notify: restart fail2ban

- name: Set fail2ban bantime to 1 hour
  become: true
  # Use lineinfile because ConfigParser rejects section=default
  lineinfile: dest=/etc/fail2ban/jail.local
      regexp="^bantime = "
      state=present
      line="bantime = 3600"

- name: Enable fail2ban filters
  become: true
  ini_file: dest=/etc/fail2ban/jail.local
    section=$item
    option=enabled
    value=true
  with_items:
  - ssh
  - ssh-ddos
  - pam-generic
  notify: restart fail2ban
